config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: "pages#dashboard"
  resources :decks do
    resources :cards, only: [:new, :create, :show]
    member do
      get :results
      get :create_new_deck_cards
    end
  end
  resources :category, only: [:new, :create]
  resources :cards, only: [:index, :edit, :update, :destroy]
  resources :card_scores, only: [:create]
end

app/views/pages/_dashboard-deck-list.html.erb
<% @decks.each do |deck| %>
  <div class="btn btn-primary deck-button">
    <%= link_to deck.name, deck_path(deck), class:"deck-link" %>
    <% if deck.scores.where(user: current_user).size >= 1 %>
      <% most_recent_user_score = deck.scores.last.total %>
      <% cards_in_deck = deck.cards.count %>
      <% hundo = deck.scores.where(user: current_user).find do |score| %>
        <% score.total == cards_in_deck %>
      <% end %>
      <% if !hundo.nil? %>
        <i class="fas fa-medal hidden-hundo"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/pages/_recently-played-cards.html.erb
<% @first_six_decks.each do |deck| %>
  <div class="recently-played-card">
    <div class="card-title-and-subtitle">
      <h3 id="dash-card-header"> <%= link_to deck.name, deck_path(deck) %> </h3>
      <h6 id="dash-card-subtitle">  <%= deck.category.name %> </h6>
    </div>
    <div class="details-box">
      <div class="cards-details-box">
        <%= link_to deck_path(deck) do %>
          <p class = "used-count"></i><%= deck.cards.count %> <%= image_tag "https://res.cloudinary.com/flashcard/image/upload/v1615289621/Landing-page%20background%20and%20logo/cards-icon.png", class: "cards-icon" %></p>
          <p class="attempt-counter"><%= deck.scores.count %><i class="far fa-play-circle cards-icon"></i></p>
        <% end %>
      </div>
    </div>
    <div class="name-and-avatar">
      <p class="user-name">Made by <%= deck.user.first_name %></p>
      <div class="card-avatar-div">
        <% if deck.user.avatar.attached? %>
          <%= cl_image_tag deck.user.avatar.key, :width=>35, :height=>35,:gravity=>"face", :crop=>"thumb", cloud_name: "flashcard", class: "card-avatar" %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/flashcard/image/upload/v1614867653/Landing-page%20background%20and%20logo/default-avatar.jpg", alt: "alttext", class: "card-avatar", alt: "alttext" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<!-- Standard container to control width -->
<div class="container-dashboard">
  <!--the div containing both the deck list on the left and the recently played div -->
  <div id="deck-list-and-recently-played-container">
    <% if @decks %>
    <div class="dashboard-left">
      <div id="deck-list-container">
        <h5 class="dashboard-subheadings-your-decks" id="deck-list-header">Your Decks:</h5>
        <%= render 'dashboard-deck-list' %>
      </div>
    </div>
    <% end %>
    <div class="dashboard-right">
      <div class="container dashboard-buttons-container">
        <%= link_to "View Your Cards", cards_path, class:"btn btn-success", id:"index-user-cards" %>
        <%= link_to "Create New Deck", new_deck_path, class:"btn btn-success", id:"create-new-deck-button" %>
        <%= link_to "Find A Deck", decks_path, class:"btn btn-success", id:"find-new-deck-button" %>
      </div>
      <h5 class="dashboard-subheadings-2" >Popular Decks:</h5>
      <div id="recently-played-container">
        <%= render 'recently-played-cards' %>
      </div>

      <div id="daily-usage">
        <h5 class="text-center">Daily Usage:</h5>
        <div class="d-inline-flex p-2 w-100 justify-content-between">
          <div>
            <h7><em>Log-ins this month:</em> <strong><%= current_user.logins_per_month %></strong> </h7>
          </div>
          <div>
            <h7><em>Decks studied this month:</em> <strong><%= current_user.decks_studied_per_month %></strong> </h7>
          </div>
          <div>
            <h7><em>Flashcard streak:</em> <strong><%= current_user.streaks %></strong></h7>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="whole-grid">
  <div id="main-content">
    <div id="page-content">
      <div  class="content">
        <%= image_tag("https://res.cloudinary.com/flashcard/image/upload/v1615200804/flashcard-logo_hrqipb.png", class:"logo") %>
        <div class="links">
          <% if user_signed_in? %>
            <h3>Welcome back, <%= (current_user.first_name).capitalize %></h3>
            <h6>Your Last Study Session: <%= current_user.last_sign_in_at.strftime("%A, %d %B") %></h6>
            <%= link_to "My Dashboard", dashboard_path, class:"btn btn-success", id:"log-in" %>
          <% else %>
            <h3>Start your revision with Flashcard, the modern way to study using flashcards. </h3>
            <%= link_to "Get Started Today!" , new_user_registration_path ,class:"btn btn-success", id:"sign-up" %>
            <%= link_to "Log-In", new_user_session_path ,class:"btn btn-primary", id:"log-in" %>
          <% end %>
        </div>
      </div>
    </div>
    <div id="page-content">
      <div class="more-info">
        <h4><%= "Question:" %></h4>
        <h5 class="indented"><%= "What is the definition of HTML?" %></h5>
        <h4><%= "Answer:" %></h4>
        <h5 class="indented" id='type-here'><%=  %></h5>
      </div>
      <div class="more-info">
        <h4><%= "<ul>" %></h4>
        <h5 class="indented"><%= "<li> Add your decks and cards... </li>" %></h5>
        <h5 class="indented"><%= "<li> Start your study session now... </li>" %></h5>
        <h5 class="indented"><%= "<li> See what other's are studying and find the most popular decks... </li>" %></h5>
        <h5 class="indented"><%= "<li> Teacher's; you can add your decks and share with your students... </li>" %></h5>
        <h4><%= "</ul>" %></h4>
      </div>
      <div class="more-info">
        <h4><%= "Question:" %></h4>
        <h5 class="indented"><%= "How to do you say 'Good Morning, How are you today?' in French?" %></h5>
        <h4><%= "Answer:" %></h4>
        <h5 class="indented" id='type-here-2'><%=  %></h5>
      </div>
    </div>
  </div>
</div>