config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: "pages#dashboard"
  resources :decks do
    resources :cards, only: [:new, :create, :show]
    member do
      get :results
      get :create_new_deck_cards
    end
  end
  resources :category, only: [:new, :create]
  resources :cards, only: [:index, :edit, :update, :destroy]
  resources :card_scores, only: [:create]
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :topics, dependent: :destroy
  has_many :decks, through: :topics
  has_many :card_scores, dependent: :destroy

  validates :question, presence: true
  validates :answer, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_question,
    against: [:question],
    using: { tsearch: { prefix: true }}
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:edit, :update, :destroy]
  before_action :set_deck, only: [:show, :create]

  def index
    @cards = policy_scope(Card)
    if params[:query].present?
      @cards = Card.where(user_id: current_user.id)
      @my_cards = @cards.search_by_question(params[:query])
    else
      @my_cards = Card.where(user_id: current_user.id)
    end
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    authorize @card
    @card.user_id = current_user.id
    if @card.save
      Topic.create(deck_id: @deck.id, card_id: @card.id)
      redirect_to create_new_deck_cards_deck_path(@deck)
    else
      render 'new'
    end
  end

  def show
    @card = @deck.cards.first
    authorize @card
  end

  def edit
  end

  def update
    @card.update(card_params)
    redirect_to cards_path
  end

  def destroy
    @card.destroy
    index
    if @cards.nil?
      redirect_to dashboard_path
    else
      redirect_to cards_path
    end
  end

  private

  def set_deck
    @deck = Deck.find(params[:deck_id])
  end

  def set_card
    @card = Card.find(params[:id])
    authorize @card
  end

  def card_params
    params.require(:card).permit(:question, :answer)
  end
end

app/views/cards/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6" id="card-edit-form">
      <%= simple_form_for(@card) do |f| %>
      <%= f.input :question %>
      <%= f.input :answer %>
      <span class="card-edit-btn">
        <%= f.submit %>
      </span>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<div class="container">
  <span class="buttons-card-index">
    <%= link_to "Back To Dashboard", dashboard_path, class: "back-to-dash-button" %>
    <button class="reveal-answers">Reveal Answers</button>
  </span>

  <h3 id="deck-search-header">Card Search</h3>

  <%= form_tag cards_path,style:"width:86%;", method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find you cards"
  %>
  <%= submit_tag "Search", class: "btn card-search-button" %>
<% end %>



  <% if current_user.cards.count != 0 %>
  <% @my_cards.each do |card| %>
    <div class="line-container-cards">
      <div class="card-container">
        <h5><strong><%= card.question %></strong></h5>
        <h5 id="card-answer-visible" class="card-answer-hide"><%= card.answer %>
      </div>
      <div id="edit-card-button">
         <%= link_to "Edit", edit_card_path(card) %>
      </div>
      <div id="delete-card-button" >
         <%= link_to "Delete", card_path(card), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
  <% else %>
    <div class="no-cards-content">
      <h3>You've not added any cards yet...</h3>
      <p>Head back to your dashboard to add some now.</p>
    </div>
  <% end %>
</div>

app/views/cards/show.html.erb
<span class="counter">
  <div class="card-total">
    <h6>No. of Cards: <h6 id="score_count_total"><%= @deck.cards.count %></h6></h6>
  </div>
  <div class="card-completed">
    <h6 class="attempt_score">No. Correct: <h6 id="score_count">0</h6></h6>
  </div>
</span>
<div class="container" id="card-study-page">
  <% @deck.cards.each_with_index do |card, index| %>
  <div id="card<%=index%>" class="card-main <%= 'hideCard' unless index.zero? %>" >
    <div class="attempt-side" id="attempt<%= index %>">
      <div class="card-question">
        <h3><%= card.question %></h3>
      </div>
      <%= simple_form_for "#{card}", remote: true do |f| %>
        <%= f.input :attempt, as: :text, id:"user_attempt", input_html: {class: "attempt_#{index}"} %>
        <%= f.hidden_field :card_id, data: {card: card.id}, class: "hidden_field", value: false %>
      <% end %>
      <span class="button-correct">
        <button class="btn flipButton" data-id="<%= index %>"><i class="fas fa-redo-alt"></i></button>
      </span>
    </div>

    <div class="answer-side hideCard" id="answer<%= index %>">
      <h5 class="question-answer-underline">Question</h5>
      <div class="card-question">
        <%= card.question %>
      </div>
      <h5 class="question-answer-underline">Correct Answer</h5>
      <div class="card-answer" id="card-answer-<%= index %>">
        <%= card.answer %>
      </div>
      <span class='info-icon'><h5 class="question-answer-underline">Your Answer </h5>
        <i class="fas fa-info" data-toggle="tooltip" data-placement="right" title="Highlighted text represent's direct matches, well done!"></i>
      </span>
      <pre><code><div class="attempt card-attempt<%= index %>">
      </div></code></pre>
      <span class="button-correct">
        <i id="correct" data-id="<%= index %>" data-card="<%= card.id %>" class="fas fa-check"></i>
        <i id="incorrect" data-id="<%= index %>" data-card="<%= card.id %>" class="fas fa-times"></i>
      </span>
    </div>
    <% @final = @deck.cards.size == index + 1 ? true : false %>
    <%= link_to "", card_scores_path(card_id: card.id, deck_id: @deck.id,correct: true, final: @final), id:"card#{index}_true", method: :post %>
    <%= link_to "", card_scores_path(card_id: card.id, deck_id: @deck.id,correct: false, final: @final), id:"card#{index}_false", method: :post %>
  </div>
  <% end %>
</div>