config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: "pages#dashboard"
  resources :decks do
    resources :cards, only: [:new, :create, :show]
    member do
      get :results
      get :create_new_deck_cards
    end
  end
  resources :category, only: [:new, :create]
  resources :cards, only: [:index, :edit, :update, :destroy]
  resources :card_scores, only: [:create]
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :scores, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :cards, through: :topics

  validates :name, presence: true, uniqueness: { scope: :category }
  validates :category, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [:name],
    associated_against: { cards: :question },
    using: { tsearch: { prefix: true } }

  def add_decks_studied_per_month
    if (Date.now = Date.today.at_beginning_of_month)
      self.add_decks_studied_per_month = sign_in_count
    else
      self.add_decks_studied_per_month = 0
    end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, except: [:index, :new, :create]

  def show
    @deck_cards = @deck.cards
    authorize @deck_cards
  end

  def index
    @decks = policy_scope(Deck)
    if params[:query].present?
      @decks = Deck.search_by_name(params[:query])
    else
      @decks = Deck.all
    end
  end

  def new
    @deck = Deck.new
    authorize @deck
  end

  def create
    @deck = Deck.new(strong_params)
    authorize @deck
    @deck.user = current_user
    if params[:deck][:category_id].present?
      category = Category.find(params[:deck][:category_id])
    elsif params[:deck][:category][:name].present?
      category = Category.create(name: params[:deck][:category][:name])
    end
    @deck.category = category if category
    if @deck.save
      redirect_to create_new_deck_cards_deck_path(@deck)
    else
      render "new"
    end
  end

  def create_new_deck_cards
    @deck.name = @deck.name.titleize
    @card = Card.new
    @deck_cards = @deck.cards
  end

  def results
  end

  def edit
  end

  def update
    @deck.update!(strong_params)
    question_keys = params[:deck][:cards].keys.select { |key| key.match?(/question/) }
    new_cards = []
    question_keys.each_with_index do | key, index|
      question = "question_#{index + 1}"
      answer = "answer_#{index + 1}"
      new_cards << Card.create(question: params[:deck][:cards][question], answer: params[:deck][:cards][answer], user_id: current_user.id)
    end
    cards = params[:deck][:card_ids].reject(&:blank?).map(&:to_i)
    new_cards = new_cards.select(&:valid?)
    if new_cards.present?
      @deck.cards = Card.where(id: cards) + new_cards
    else
      @deck.cards = Card.where(id: cards)
    end
    redirect_to edit_deck_path(@deck)
  end

  def destroy
    @user = current_user
    @deck.destroy
    redirect_to dashboard_path
  end

  private

  def strong_params
    params.require(:deck).permit(:name)
  end

  def set_deck
    @deck = Deck.find(params[:id])
    authorize @deck
  end
end

app/views/decks/_first_previous.html.erb
<% if @deck.scores.where(user: current_user).size > 1 %>
  <% @score = @deck.scores.where(user: current_user)[-2].card_scores.find_by(card_id: score.card.id) %>

  <% if @score.nil? %>
    <td class='incorrect-table'><i class="fas fa-times"></i></td>
  <% elsif @score.correct %>
    <td class='correct-table'><i class="fas fa-check"></i></td>
  <% else %>
    <td class='incorrect-table'><i class="fas fa-times"></i></td>
  <% end %>
<% end %>

app/views/decks/_results_text_query.html.erb
<% if !@deck.scores.last.nil? %>
  <% most_recent_user_score = @deck.scores.last.total %>
  <% cards_in_deck = @deck.cards.count.to_f %>
  <% user_percentage = (most_recent_user_score/cards_in_deck * 100).round%>
  <% user_score_string_fraction = "#{most_recent_user_score}/#{cards_in_deck.to_i}" %>
  <% if user_percentage <= 40 %>
    <div class="big-percent">
      You Just Scored <%= user_percentage %>%
    </div>
    <div class="display-message">
      <%= "You could use some extra time on this deck, you got #{user_score_string_fraction}." %>
    </div>
    <%= link_to "Study this deck again", deck_card_path(@deck), class: "btn retry-button" %>
  <% elsif user_percentage <= 75 %>
    <div class="big-percent">
      You Just Scored <%= user_percentage %>%
    </div>
    <div class="display-message">
      <%= "Well done! you got #{user_score_string_fraction} this try!" %>
    </div>
  <% elsif user_percentage >= 100 %>
    <div class="big-percent" id="confetti">
      You Just Scored 100%!
    </div>
      <i class="fas fa-trophy"></i>
  <% else %>
    <div class="big-percent">
      You Just Scored <%= user_percentage %>%
    </div>
    <div class="display-message">
      <%= "Wow! Pat Yourself On The Back You Got #{user_score_string_fraction} This Try!" %>
    </div>
  <% end %>
<% else %>
  <p> Umm... you're not supposed to be here... </p>
  <p> Please score on a deck before coming to this page! </p>
<% end %>

app/views/decks/_second_previous.html.erb
<% if @deck.scores.where(user: current_user).size > 2 %>
  <% @score = @deck.scores.where(user: current_user)[-3].card_scores.find_by(card_id: score.card.id) %>
  <% if @score.nil? %>
    <td class='incorrect-table'><i class="fas fa-times"></i></td>
  <% elsif @score.correct %>
    <td class='correct-table'><i class="fas fa-check"></i></td>
  <% else %>
    <td class='incorrect-table'><i class="fas fa-times"></i></td>
  <% end %>
<% end %>

app/views/decks/create_new_deck_cards.html.erb
<div class="container">
  <div class="add-new-card">
    <div class="question-form">
      <h4>Add a New Card</h4>
      <%= simple_form_for [@deck, @card], remote: true, method: :post do |f| %>
        <%= f.input :question, as: :text %>
        <%= f.input :answer, as: :text %>
        <%= f.submit "Add Card", class: "btn btn-success", id:"card-add-button"%>
      <% end %>
    </div>
    <div class="cards-container">
        <div class="text-center">
    <h4><%= @deck.name %>'s Current Cards</h4>
    <p><%= @deck.category.name %></p>
  </div>
      <% @deck_cards.each do |card| %>
        <div class="card-overview-deck">
          <%= card.question %>
        </div>
      <% end %>
    </div>
  </div>

  <span class="links-to-pages">
    <%= link_to "Add existing cards", edit_deck_path(@deck), class: "btn links-buttons" %>
    <%= link_to "Back to dashboard", dashboard_path, class: "btn links-buttons" %>
  </span>
</div>

app/views/decks/edit.html.erb
<div class="container">
  <%= link_to "Back to overview", deck_path, class: "btn edit-deck-back-button" %>
  <div id="deck-edit-div">
    <h3>Edit Your <%= @deck.name %> Deck:</h3>
    <%= simple_form_for @deck, url: deck_path(@deck), method: :patch, html: { class: 'edit_deck_category' } do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <p class="edit-table-field-header">Name</p>
      <%= f.input :name, label: false %>
      <p class="edit-table-field-header">Category</p>
      <%= f.association :category, label: false, input_html: { class: 'select2' }  %>
      <%= f.association :cards, label_method: :question, value_method: :id, input_html: {  class: 'select2', multiple: true } %>

      <%= f.simple_fields_for :cards do |card| %>
        <button id="hidden_button_edit" type="button">
          Create New Card
        </button>
        <span class="update-btn">
          <%= f.submit %>
        </span>
        <div class="d-none hidden_form" , id="add-deck-btn" >
          <%= card.input :question_1 %>
          <%= card.input :answer_1 %>
          <span id="add-card-btn" >
            <input type="submit" name="commit" value="Add Card" data-disable-with="Add Card">
          </span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/decks/index.html.erb
<div class="container" id="deck-index-search-page">

  <%= link_to "Back To Dashboard", dashboard_path, class: "back-to-dash-button" %>

  <h3 id="deck-search-header">Deck Search</h3>

    <div class="search-bar select2">

        <%= form_tag decks_path, style: "display: flex;display: flex; justify-content: space-between; width: 91.7%; margin-bottom: -25px;", method: :get do %>
          <%  %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control select2 search-form",

          placeholder: "Search through public decks..."%>
          <%= submit_tag "Search", class: "btn btn-primary deck-index-search-button", id: "deck-search-button" %>
        <% end %>

  </div>
  <% shuffled_decks = @decks.shuffle %>
  <% shuffled_decks.each do |deck| %>
    <div class="line-container">
      <div class="deck-container">
        <h5><strong><%= deck.name %></strong> ~ <%= deck.cards.count %> <%= image_tag "https://res.cloudinary.com/flashcard/image/upload/v1615289621/Landing-page%20background%20and%20logo/cards-icon.png", class: "cards-icon" %> </h5>
        <div class="username-avatar">
          <h5><%= deck.user.first_name %></h5>
          <% if deck.user.avatar.attached? %>
            <%= cl_image_tag deck.user.avatar.key, cloud_name: "flashcard", class: "card-avatar" %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/flashcard/image/upload/v1614867653/Landing-page%20background%20and%20logo/default-avatar.jpg", alt: "alttext", class: "card-avatar", alt: "alttext" %>
          <% end %>
        </div>
      </div>
      <div class="study-now-container">
         <%= link_to "Study now", deck_path(deck) %>
      </div>
    </div>
  <% end %>
</div>

app/views/decks/new.html.erb
<div class="container">

  <%= link_to "Back To Dashboard", dashboard_path, class: "back-to-dash-button", id: "deck-new-back-to-dash-button" %>

  <div class="row justify-content-center" id="create-new-deck-box">
		<div class="col-6" id="create-deck-form">
      <h3 id="new-deck-heading" >Time to make a new deck!</h3>
			<%= simple_form_for @deck do |f| %>
  			<%= f.input :name %>
  			<%= f.association :category, required: false %>
                <%= f.simple_fields_for :category do |category|%>
                <p> or </p>
                  <button id="hidden_button_new" type="button">
                    Create A New Category
                  </button>
                  <div class="d-none hidden_form">
                    <%= category.input :name, id: "input-name-form" %>
                  </div>
                <% end %>
  			<%= f.submit "Create Deck", class: "btn", id:"create-deck-button" %>
			<% end %>
		</div>
	</div>
</div>

app/views/decks/results.html.erb
<div class="dash-buttons">
<%= link_to "Back To Dashboard", dashboard_path, class: "btn results-buttons"  %>
<%= link_to "Back To Deck Overview", deck_path(@deck), class: "btn results-buttons"  %>
</div>
<div id="results-container"></div>
<style type="text/css">
  #results-container{
    position: absolute;
    width: 100vw;
    height:100vh;
  }
  #results-container canvas{
    width: 100vw;
    height: 100vh;
  }
</style>

<div class="container" >
  <h3 class="title-results">Your Results For <%= @deck.name %>: </h3>
  <div class="row justify-content-center">
    <div class="results-in-con">
      <div class="col-12 results-box">
        <%= render 'results_text_query' %>
      </div>
    </div>
  </div>

  <div class="table-of-results">
  <table class="results-table">
    <thead>
      <tr>
        <th class="table-headers">Question</th>
        <th class="table-headers">Answer</th>
        <th class="table-headers">Just Now</th>
        <% if @deck.scores.where(user: current_user).size > 1 %>
          <th class="table-headers"><%= @deck.scores.where(user: current_user).last.created_at.strftime("%D %R") %></th>
        <% end %>
        <% if @deck.scores.where(user: current_user).size > 2 %>
          <th class="table-headers"><%= @deck.scores.where(user: current_user)[-3].created_at.strftime("%D %R") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @deck.scores.where(user: current_user).last.card_scores.each do |score| %>
      <tr class="table-row">
        <td class="card-question-results"><%= score.card.question %></td>
        <td class="card-answer-results"><%= score.card.answer %></td>
        <% if score.nil? %>
          <td class='incorrect-table'><i class="fas fa-times"></i></td>
        <% elsif score.correct %>
          <td class='correct-table'><i class="fas fa-check"></i></td>
        <% else %>
          <td class='incorrect-table'><i class="fas fa-times"></i></td>
        <% end %>
        <%= render 'first_previous', score: score %>
        <%= render 'second_previous', score: score %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/decks/show.html.erb
<div class="container">
  <%= link_to "Back To Dashboard", dashboard_path, class:"back-to-dash-button"%>
  <h2 id="overivew-header"><%= @deck.name %></h2>
  <% if @deck.cards.count != 0 %>
    <h4 class="text-center"><%= @deck.cards.count %> <%= image_tag "https://res.cloudinary.com/flashcard/image/upload/v1615289621/Landing-page%20background%20and%20logo/cards-icon.png", class: "cards-icon" %></h4>
  <% end %>

  <div class="buttons-container">
    <% if policy(@deck).edit? %>
      <%= link_to "Edit This Deck", edit_deck_path %>
    <% end %>
    <% if !@deck.cards.empty? %>
      <%= link_to "Study This Deck", deck_card_path(@deck), id: "deck-show-study-deck-button" %>
    <% end %>
    <% if policy(@deck).destroy? %>
      <%= link_to "Delete This Deck", deck_path , method: :delete, data: { confirm: 'Are you sure you want to delete?' }, id: "deck-show-delete-deck-button" %>
    <% end %>
  </div>

  <% if @deck.cards.count != 0 %>
    <h4 id="cards-show-header">Cards:</h4>
    <div id="cards-container">
      <% @deck_cards.each do |card| %>
        <div class="card-overview">
           <%= card.question %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="no-cards-content">
      <h3>You've not added any cards yet...</h3>
      <p>Head back to your dashboard to add some now.</p>
    </div>
  <% end %>
</div>